# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4697f18ecce696b89bb87cfc4d187c69e238f629849fa908ef1d813e3e7066dc06d33d089b1cf62b8dddf3ea305d9c0411f55194c9f7f0a87d273a9a45a1c24

test:
  secret_key_base: d7eabc2b15953157bb917e62e2e5da3a57f41a64c7bd50303298a84979f25e9defc6f011b2e9c4405db723abc90970bffc2bd633f949a25e0f49d881daeecf06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
